# Default values for a papyrus-backup deployment.

# The verbosity level of logs ("debug", "info", "error", etc.)
rustLogLevel: "papyrus=DEBUG"

# The Docker image (including any tag and repository name)
deployment:
  image:
    repository: us.gcr.io/starkware-dev/papyrus-backup
    tag: 0.2.0
services: []
# Persistent volume claim variables for a papyrus pod.
pvc:
  size: 1000Gi
  storageClass: premium-rwo

backup:
  enabled: true
  aws:
    s3BucketName: papyrus-backup
    s3BucketRegion: us-east-2
