{
 "title": "test",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Main Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts Panel", "type": "alertlist", "gridPos": { "h": 27, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "Unsynced headers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"test\"} - papyrus_header_marker{kubernetes_namespace=\"test\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unsynced bodies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"test\"} - papyrus_body_marker{kubernetes_namespace=\"test\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unsynced state diffs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"test\"} - papyrus_state_marker{kubernetes_namespace=\"test\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unsynced compiled classes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"test\"} - papyrus_compiled_class_marker{kubernetes_namespace=\"test\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests Rate - Execute Functions",
   "type": "timeseries",
   "description": "Rate of requests for methods that change Starknet",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(sum(rpc_incoming_requests{kubernetes_namespace=\"test\", method=~\"addDeclareTransaction|addDeployAccountTransaction|addInvokeTransaction\"})[10m:])",
     "legendFormat": "Incoming requests rate (in 10 mins)"
    }
   ]
  },
  {
   "title": "Requests Rate - Call Functions",
   "type": "timeseries",
   "description": "Rate of requests for methods that query Starknet",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "rate(sum(rpc_incoming_requests{kubernetes_namespace=\"test\", method!~\"addDeclareTransaction|addDeployAccountTransaction|addInvokeTransaction\"})[10m:])",
     "legendFormat": "Incoming requests rate (in 10 mins)"
    }
   ]
  },
  {
   "title": "Starknet Block Creation Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(papyrus_central_block_marker{kubernetes_namespace=\"test\"}[4m])*225)",
     "legendFormat": "Number of Blocks"
    }
   ]
  },
  {
   "title": "Latency Alert - Execute Functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "addDeclareTransaction OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"addDeclareTransaction\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "addDeclareTransaction NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"addDeclareTransaction\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "addDeployAccountTransaction OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"addDeployAccountTransaction\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "addDeployAccountTransaction NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"addDeployAccountTransaction\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "addInvokeTransaction OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"addInvokeTransaction\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "addInvokeTransaction NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"addInvokeTransaction\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Latency Alert - Call Functions - Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "blockHashAndNumber OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"blockHashAndNumber\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "blockHashAndNumber NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"blockHashAndNumber\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "blockNumber OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"blockNumber\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "blockNumber NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"blockNumber\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getBlockTransactionCount OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getBlockTransactionCount\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getBlockTransactionCount NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getBlockTransactionCount\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getBlockWithTxHashes OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getBlockWithTxHashes\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getBlockWithTxHashes NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getBlockWithTxHashes\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getBlockWithTxs OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getBlockWithTxs\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getBlockWithTxs NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getBlockWithTxs\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Latency Alert - Call Functions - Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 }
  },
  {
   "title": "getTransactionByBlockIdAndIndex OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getTransactionByBlockIdAndIndex\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getTransactionByBlockIdAndIndex NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 66 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getTransactionByBlockIdAndIndex\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getTransactionByHash OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getTransactionByHash\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getTransactionByHash NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 66 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getTransactionByHash\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getTransactionReceipt OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getTransactionReceipt\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getTransactionReceipt NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 73 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getTransactionReceipt\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "pendingTransactions OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"pendingTransactions\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "pendingTransactions NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 73 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"pendingTransactions\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Latency Alert - Call Functions - Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "getClass OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getClass\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getClass NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 81 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getClass\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getClassAt OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getClassAt\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getClassAt NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 81 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getClassAt\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getClassHashAt OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getClassHashAt\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getClassHashAt NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 88 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getClassHashAt\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Latency Alert - Call Functions - Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "title": "call OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"call\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "call NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 96 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"call\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "chainId OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"chainId\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "chainId NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 96 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"chainId\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "estimateFee OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"estimateFee\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "estimateFee NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 103 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"estimateFee\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getNonce OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getNonce\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getNonce NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 103 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getNonce\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getEvents OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getEvents\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getEvents NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 110 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getEvents\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getStorageAt OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getStorageAt\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getStorageAt NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 110 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getStorageAt\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getStateUpdate OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getStateUpdate\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "getStateUpdate NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 117 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"getStateUpdate\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "syncing OLD_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"syncing\",version=\"OLD_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "syncing NEW_VERSION Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 117 },
   "targets": [
    {
     "expr": "rpc_request_latency_seconds{kubernetes_namespace=\"test\", method=\"syncing\",version=\"NEW_VERSION\",quantile=\"0.95\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  }
 ]
}