ignore:
  - "crates/test_utils"
  - "crates/papyrus_load_test"
  - "crates/papyrus_node/src/bin/*integration_test.rs"
  - "crates/**/*test*.rs"
coverage:
  status:
    project:
      default:
        target: auto # set the target coverage to the value of the parent commit
        threshold: 0% # pct of drop in coverage that is still considered as success
        informational: true # if true does not fail the CI is coverage is bellow the target value
        only_pulls: true # run only on PRs
    patch:
      default:
        target: 100%
        threshold: 0%
        informational: true
        only_pulls: true
