{
 "title": "Papyrus-integration-ori",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"papyrus.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Header latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "papyrus_header_latency{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Central ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Header",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 1, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_header_marker{kubernetes_namespace=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Header",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_header_marker{kubernetes_namespace=\"$Pod\"} * 1000000",
     "legendFormat": "Header"
    },
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$Pod\"} * 1000000",
     "legendFormat": "Central"
    }
   ]
  },
  {
   "title": "Body",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_body_marker{kubernetes_namespace=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Body",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_body_marker{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Body"
    },
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Central"
    }
   ]
  },
  {
   "title": "State update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_state_marker{kubernetes_namespace=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "State update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_state_marker{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Base layer"
    },
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Central"
    }
   ]
  },
  {
   "title": "Compiled class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 1, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_compiled_class_marker{kubernetes_namespace=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Compiled class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_compiled_class_marker{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Header"
    },
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Central"
    }
   ]
  },
  {
   "title": "Base layer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_base_layer_marker{kubernetes_namespace=\"$Pod\"}"
    }
   ]
  },
  {
   "title": "Base layer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_base_layer_marker{kubernetes_namespace=\"$Pod\"} or vector(0)",
     "legendFormat": "Base layer"
    },
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "Central"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory GB",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
     "legendFormat": "container_memory_usage_bytes (GB)"
    },
    {
     "expr": "container_memory_mapped_file{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
     "legendFormat": "container_memory_mapped_file (GB)"
    },
    {
     "expr": "container_memory_rss{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
     "legendFormat": "container_memory_rss (GB)"
    },
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
     "legendFormat": "container_memory_max_usage_bytes (GB)"
    },
    {
     "expr": "container_memory_swap{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
     "legendFormat": "container_memory_swap (GB)"
    },
    {
     "expr": "container_spec_memory_limit_bytes{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
     "legendFormat": "container_spec_memory_limit_bytes (GB)"
    }
   ]
  },
  {
   "title": "Gateway incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "gateway_incoming_requests{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "gateway_failed_requests{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "gateway_request_latency_seconds_count{kubernetes_namespace=\"$Pod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}