{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "papyrus.name" . }}-aws-creds
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.backup.aws.access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.aws.secret_access_key | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.backup.aws.s3_bucket_region | b64dec }}
{{- end }}
