apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "papyrus.name" . }}-config
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
data:
  PAPYRUS_ETHEREUM_API_URL: "{{ .Values.ethereumApiUrl }}"
  RUST_LOG: "{{ .Values.rustLogLevel }}"
