{{- if and ( not .Values.backup.enabled ) .Values.p2p.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" . }}-p2p
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.p2p.service.annotations }}
    {{ toYaml .Values.p2p.service.annotations | nindent 4 }}
  {{- end}}
spec:
  selector:
    {{- include "papyrus.selectorLabels" . | nindent 6 }}
  type: {{ .Values.p2p.service.type }}
  {{- if and (eq .Values.p2p.service.type "LoadBalancer") .Values.p2p.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.p2p.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: p2p
    port: {{ .Values.p2p.service.port }}
    protocol: {{ .Values.p2p.service.protocol }}
    targetPort: p2p
{{- end }}