{{- if and ( not .Values.backup.enabled ) .Values.p2p.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" . }}-p2p
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "papyrus.selectorLabels" . | nindent 6 }}
  type: {{ .Values.p2p.service.type }}
  ports:
  - name: p2p
    port: {{ .Values.p2p.service.port }}
    protocol: {{ .Values.p2p.service.protocol }}
    targetPort: p2p
<<<<<<< HEAD
=======
    {{- if and (eq .Values.p2p.service.type "NodePort") .Values.p2p.service.nodePort }}
    nodePort: {{ .Values.p2p.service.nodePort }}
    {{- end }}
>>>>>>> 009ca93a3c6613c4331390333df158fc31ed809d
{{- end }}