{{- if not .Values.backup.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" . }}-svc
  labels:
    {{- include "papyrus.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "papyrus.selectorLabels" . | nindent 6 }}
  type: {{ .Values.service.type }}
  ports:
  {{- if and .Values.service.ports.rpc .Values.service.ports.rpc.enabled }}
  - name: rpc
    port: {{ .Values.service.ports.rpc.port }}
    protocol: {{ .Values.service.ports.rpc.protocol }}
    targetPort: rpc
    {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.rpc.nodePort }}
    nodePort: {{ .Values.service.ports.rpc.nodePort }}
    {{- end }}
  {{- end }}
  {{- if and .Values.service.ports.monitoring .Values.service.ports.monitoring.enabled }}
  - name: monitoring
    port: {{ .Values.service.ports.monitoring.port }}
    protocol: {{ .Values.service.ports.monitoring.protocol }}
    targetPort: monitoring
    {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.monitoring.nodePort }}
    nodePort: {{ .Values.service.ports.monitoring.nodePort }}
    {{- end }}
  {{- end }}
{{- end }}