{{- if not .Values.backup.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" $ }}-svc
  labels:
    {{- include "papyrus.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "papyrus.selectorLabels" $ | nindent 6 }}
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.rpc.enabled }}
  - name: {{ template "papyrus.name" $ }}-port
    protocol: {{ .Values.service.rpc.protocol }}
    port: {{ .Values.service.rpc.port }}
    targetPort: {{ .Values.service.rpc.port }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.rpc.nodePort }}
    nodePort: {{ .Values.service.rpc.nodePort }}
    {{- end }}
  {{- end}}
  {{- if .Values.service.monitoring.enabled }}
  - name: {{ template "papyrus.name" $ }}-monitoring
    protocol: {{ .Values.service.monitoring.protocol }}
    port: {{ .Values.service.monitoring.port }}
    targetPort: {{ .Values.service.monitoring.port }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.monitoring.nodePort }}
    nodePort: {{ .Values.service.monitoring.nodePort }}
    {{- end }}
  {{- end}}
  {{- if .Values.service.p2p.enabled }}
  - name: {{ template "papyrus.name" $ }}-p2p
    protocol: {{ .Values.service.p2p.protocol }}
    port: {{ .Values.service.p2p.port }}
    targetPort: {{ .Values.service.p2p.port }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.p2p.nodePort }}
    nodePort: {{ .Values.service.p2p.nodePort }}
    {{- end }}
  {{- end}}
{{- end }}