{{- if not .Values.backup.enabled }}
{{- range $k, $v := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" $ }}-{{ $k }}
  labels:
    {{- include "papyrus.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "papyrus.selectorLabels" $ | nindent 6 }}
  type: {{ $v.type }}
  ports:
  - name: {{ template "papyrus.name" $ }}-port
    protocol: "{{ $v.protocol }}"
    port: {{ $v.port }}
    targetPort: {{ $v.port }}
{{- end }}
{{- end }}
