apiVersion: v1
kind: Service
metadata:
  name: {{ template "papyrus.name" . }}-rpc
spec:
  selector:
    app: papyrus
  type: {{ .Values.services.rpc.type }}
  ports:
  - name: {{ template "papyrus.name" . }}-port
    protocol: "{{ .Values.services.rpc.protocol }}"
    port: {{ .Values.services.rpc.port }}
    targetPort: {{ .Values.services.rpc.port }}
