[package]
name = "papyrus_proc_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.15"
quote = "1.0.26"

[lib]
proc-macro = true
