- - GatewayConfig.chain_id
  - The chain to follow. For more details see https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#chain-id.
  - SN_MAIN
- - GatewayConfig.server_address
  - IP:PORT of the node's JSON-RPC server.
  - 0.0.0.0:8080
- - GatewayConfig.max_events_chunk_size
  - Maximum chunk size supported by the node in get_events requests.
  - '1000'
- - GatewayConfig.max_events_keys
  - Maximum number of keys supported by the node in get_events requests.
  - '100'
