[package]
name = "starknet_client"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_matches = { version = "1.5.0" }
field_names = { version = "0.2.0" }
log = { version = "0.4" }
mockito = { version = "0.31.0" }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.81" }
starknet_api = { path = "../starknet_api" }
thiserror = { version = "1.0.31" }
tokio = { version = "1.18.2", features = ["full","sync"] }
url = { version = "2.2.2" }
web3 = { version = "0.18.0" }
