[package]
name = "starknet_client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1.56" }
log = { version = "0.4" }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.81" , features = ["arbitrary_precision"]}
starknet_api = { path = "../starknet_api" }
thiserror = { version = "1.0.31" }
tokio = { version = "1.18.2", features = ["full","sync"] }
tokio-retry = { version = "0.3" }
url = { version = "2.2.2" }
web3 = { version = "0.18.0" }
mockall = { version = "0.11.2" }

[dev-dependencies]
assert = { version = "0.0.4" }
assert_matches = { version = "1.5.0" }
mockito = { version = "0.31.0" }
