[package]
name = "papyrus_config"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["string"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
itertools.workspace = true
