[package]
name = "dump_declared_classes"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
papyrus_storage = { path = "../papyrus_storage", version = "0.0.5" }
