name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [main, dan/main/helm]

env:
  NAMESPACE: papyris-${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CI_SA_CREDENTIALS }}"

      - id: "get-credentials"
        name: Get GKE credentials
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: "${{ secrets.GKE_CI_CLUSTER_NAME }}"
          location: "${{ secrets.GKE_CI_CLUSTER_REGION }}"

      - id: "helm-install"
        name: Deploy to Kubernetes using helm
        run: |
          helm upgrade --install papyrus deployments/helm/ \
          --namespace $NAMESPACE \
          --create-namespace \
          --values deployments/helm/CI/default_values.yaml \
          --set ingress.host=${{ secrets.GKE_CI_HOST }}

      # TODO: remove when public.
      - name: Add k8s secret to access container registry
        run: |
          kubectl --namespace=$NAMESPACE create secret docker-registry regcred \
          --docker-server=ghcr.io \
          --docker-username=${{ secrets.GHCR_USERNAME }} \
          --docker-password=${{ secrets.GHCR_TOKEN }}

      - name: Run load test
        run: kubectl -namespace=$NAMESPACE apply -f deployments/helm/CI/load_test_job.yaml

      # - name: Clean deployment
      #   run: helm uninstall $NAMESPACE
