name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [main, eran/main/helm]

jobs:
  deploy-benchmark-teardown:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set a unique run identifier
        run: echo "UNIQE_ID=${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_ENV

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CI_SA_CREDENTIALS }}"

      - id: "get-credentials"
        name: Get GKE credentials
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: "${{ secrets.GKE_CI_CLUSTER_NAME }}"
          location: "${{ secrets.GKE_CI_CLUSTER_REGION }}"

      - id: "helm-install"
        name: Deploy to Kubernetes using helm
        run: |
          helm upgrade --install papyrus-${UNIQE_ID} deployments/helm/ \
          --namespace papyrus \
          --values deployments/helm/CI/default_values.yaml \
          --set ingress.host=${{ secrets.GKE_CI_HOST }}-${UNIQE_ID} \

      - name: Wait for papyrus pods to be ready
        run: kubectl --namespace papyrus rollout status deployment papyrus-${UNIQE_ID}

      - name: Set load_test durration
        run: |
          # The amount of time we want the load test to run
          echo "DURRATION=1m" >> $GITHUB_ENV
          # The max amount of time we are willing to wait for the load test to complete (must be greater then DURRATION)
          echo "DURRATION_TIMEOUT=5m" >> $GITHUB_ENV

      - name: Run load test
        run: sh -c "deployments/helm/CI/run_benchmark.bash ${UNIQE_ID} ${DURRATION} ${DURRATION_TIMEOUT}"

      # - name: Clean the deployment
      #   if: always()
      #   run: helm delete --namespace papyrus papyrus-${UNIQE_ID}
